#!/usr/bin/env python
"""
NAME

    reddit-background

SYNOPSIS

    reddit-backgrounds [--desktop <DESKTOP>] [-h --help] [SUBREDDITS]

DESCRIPTION

    Set Mac OS X desktop backgrounds to images from pulled from Reddit.

EXAMPLES

    reddit-backgrounds CarPorn:top:10:week {seasonal} EarthPorn:new

AUTHOR

    Rick Harris <rconradharris@gmail.com>
"""
import ConfigParser
import argparse
import collections
import datetime
import json
import os
import random
import shutil
import subprocess
import sys
import urllib2
import uuid


CONFIG_PATH = "~/.reddit-background.conf"
DOWNLOAD_DIRECTORY = "~/.background-images"

def _run_apple_script(script):
    return subprocess.check_output(['osascript', '-e', script])


def _set_desktop_background(idx, filename):
    script = 'tell application "System Events" to set picture of item'\
             ' {idx} of (a reference to every desktop) to "{filename}"'\
             .format(idx=idx, filename=filename)
    return _run_apple_script(script)


def _get_number_of_desktops():
    script = 'tell application "System Events" to return count of a'\
             ' reference to every desktop'
    return int(_run_apple_script(script).strip())
    

def _urlopen(url):
    user_agent = "Mozilla/5.0 (X11; U; Linux i686) Gecko/20071127 Firefox/2.0.0.11" 
    opener = urllib2.build_opener()
    opener.addheaders = [('User-Agent', user_agent)]
    return opener.open(url)
    

def _download(url, filename):
    response = _urlopen(url)
    try:
        with open(filename, 'w') as f:
            f.write(response.read())
    finally:
        response.close()


def _download_image(image_url):
    dirname = os.path.expanduser(DOWNLOAD_DIRECTORY)
    basename = "%s.jpg" % uuid.uuid4()
    filename = os.path.join(dirname, basename)
    _download(image_url, filename)
    return filename


def _select_and_download_image_for_desktop(image_urls):
    image_urls = image_urls[:]

    random.shuffle(image_urls)

    for image_url in image_urls:
        try:
            return _download_image(image_url)
        except urllib2.HTTPError:
            pass  # Try next image...


def _clear_download_directory():
    dirname = os.path.expanduser(DOWNLOAD_DIRECTORY)
    if os.path.exists(dirname):
        shutil.rmtree(dirname)
    os.makedirs(dirname)


def _get_northern_hemisphere_season():
    """Source: http://stackoverflow.com/questions/16139306/determine-season-given-timestamp-in-python-using-datetime"""
    day = datetime.date.today().timetuple().tm_yday
    spring = range(80, 172)
    summer = range(172, 264)
    autumn = range(264, 355)
    if day in spring:
      return 'spring'
    elif day in summer:
      return 'summer'
    elif day in autumn:
      return 'autumn'
    else:
      return 'winter'


class Subreddit(object):
    def __init__(self, name, sort='top', limit=25, timeframe='week'):
        self.name = name
        self.sort = sort
        self.limit = limit
        self.timeframe = timeframe

    @staticmethod
    def _fetch_subreddit_data(subreddit, sort, limit, timeframe):
        url = 'http://reddit.com/r/{subreddit}/{sort}.json?t={timeframe}&limit={limit}'
        url = url.format(subreddit=subreddit,
                         sort=sort,
                         timeframe=timeframe,
                         limit=limit)
        response = _urlopen(url)
        try:
            return json.loads(response.read())
        finally:
            response.close()

    @staticmethod
    def _get_image_urls_from_data(data):
        image_urls = []
        for child in data['data']['children']:
            url = child['data']['url']
            if url.endswith('.jpg'):
                image_urls.append(url)
            elif 'imgur.com' in url:
                url += '.jpg'
                image_urls.append(url)

        return image_urls

    def fetch_image_urls(self):
        data = self._fetch_subreddit_data(
                self.name, self.sort, self.limit, self.timeframe)
        return self._get_image_urls_from_data(data)

    @classmethod
    def create_from_token_parts(cls, token_parts):
        args = ('name', 'sort', 'limit', 'timeframe')
        ddict = {}
        for arg, value in zip(args, token_parts):
            ddict[arg] = value
        return cls(**ddict)


def _parse_subreddit_token(token):
    token_parts = token.split(':')

    name = token_parts[0]

    if name == '{seasonal}':
        token_parts[0] = '%sporn' % _get_northern_hemisphere_season()

    return Subreddit.create_from_token_parts(token_parts)


def _get_desktop_range():
    num_desktops = _get_number_of_desktops()
    return map(lambda x: x + 1, range(num_desktops))


def _read_config_file(subreddits_by_desktop):
    path = os.path.expanduser(CONFIG_PATH)

    if not os.path.exists(path):
        return

    config = ConfigParser.ConfigParser()

    with open(path) as f:
        config.readfp(f)

    def get_subreddits_for_section(section):
        tokens = map(lambda x: x.strip(),
                     config.get(section, 'subreddits').split(','))
        subreddits = []
        for token in tokens:
            subreddit = _parse_subreddit_token(token)
            subreddits.append(subreddit)
        return subreddits

    sections = config.sections()

    desktops = _get_desktop_range()

    for desktop in desktops:
        section = 'desktop{0}'.format(desktop)
        if section in sections:
            subreddits = get_subreddits_for_section(section)
            subreddits_by_desktop[desktop] = subreddits
        elif 'default' in sections:
            subreddits = get_subreddits_for_section('default')
            subreddits_by_desktop[desktop] = subreddits


def _handle_cli_options(subreddits_by_desktop):
    parser = argparse.ArgumentParser(
        description='Set desktop background image from reddit')
    parser.add_argument('subreddits', metavar='SUBREDDITS', nargs='*',
                       help='A list of subreddits')
    parser.add_argument('--desktop', type=int, default=0,
            help='Only set background for this desktop'
                 ' (default: Set all desktops)')

    args = parser.parse_args()

    if args.desktop:
        desktops = [args.desktop]
    else:
        desktops = _get_desktop_range()

    for token in args.subreddits:
        subreddit = _parse_subreddit_token(token)
        for desktop in desktops:
            subreddits_by_desktop[desktop].append(subreddit)


def _use_defaults(subreddits_by_desktop):
    desktops = _get_desktop_range()
    for desktop in desktops:
        # Seasonal seems like a pretty good default
        subreddit = _parse_subreddit_token('{seasonal}')
        subreddits_by_desktop[desktop].append(subreddit)


def main():
    subreddits_by_desktop = collections.defaultdict(list)

    _handle_cli_options(subreddits_by_desktop)

    if not subreddits_by_desktop:
        _read_config_file(subreddits_by_desktop)

    if not subreddits_by_desktop:
        _use_defaults(subreddits_by_desktop)

    _clear_download_directory()

    for desktop, subreddits in subreddits_by_desktop.iteritems():
        # Accumulate images URL across subreddits
        image_urls = []
        for subreddit in subreddits:
            image_urls.extend(subreddit.fetch_image_urls())

        # Pick one
        filename = _select_and_download_image_for_desktop(image_urls)

        # If we found one, set the background
        if filename:
            _set_desktop_background(desktop, filename)


if __name__ == "__main__":
    main()
